title: WELCOME TO INSTABLOG GH
description: 'Voracious blog brings to you amazing content on lifestyle '
social_link: insta_bloggh
social_username: insta_bloggh
github_repo: devofori
github_username: devofori
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /insta_bloggh
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
